import type { Metadata } from "next";
import "./globals.css";
import ProviderI18Next from "@/components/ProviderI18Next/i18next-provider";
import { Roboto_Mono } from "next/font/google";

const robotoMono = Roboto_Mono({
  subsets: ["latin", "cyrillic"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
    <html lang="en">
      <body className={robotoMono.className}>
       <ProviderI18Next>{children}</ProviderI18Next>
      </body>
    </html>
  );
}