import { Project } from "@/types/projectsData";

export const projectData: Project[] = [
  {
    id: 1,
    titleKey: "project1_title",
    descriptionKey: "project1_description",
    image: "/project/crm-rest.jpg",
    dev: [
      "/svg-icons/reactts.svg",
      "/svg-icons/node.svg",
      "/svg-icons/vitejs.svg",
      "/svg-icons/material-ui.svg",
      "/svg-icons/mongodb.svg",
      "/svg-icons/light-redux.svg",
    ],
    link: "https://restoraunt-admin-panel-x3l2.vercel.app/login",
  },
  {
    id: 9,
    titleKey: "project9_title",
    descriptionKey: "project9_description",
    image: "/project/card-game.jpg",
    dev: [
      "/svg-icons/reactts.svg",
      "/svg-icons/js.svg",
      "/svg-icons/vitejs.svg",
      "/svg-icons/tailwindcss.svg",
      "/svg-icons/light-redux.svg",
    ],
    link: "https://card-game-1chn.vercel.app/",
  },
  {
    id: 10,
    titleKey: "project10_title",
    descriptionKey: "project10_description",
    image: "/project/filters-component.jpg",
    dev: [
      "/svg-icons/reactts.svg",
      "/svg-icons/js.svg",
      "/svg-icons/vitejs.svg",
      "/svg-icons/tailwindcss.svg",
      "/svg-icons/light-redux.svg",
    ],
    link: "https://test-wwt-frontend-tech-task.vercel.app/",
  },
  {
    id: 11,
    titleKey: "project11_title",
    descriptionKey: "project11_description",
    image: "/project/slider-rew-component.jpg",
    dev: [
      "/svg-icons/reactts.svg",
      "/svg-icons/js.svg",
      "/svg-icons/vitejs.svg",
      "/svg-icons/tailwindcss.svg",
      "/svg-icons/light-redux.svg",

    ],
    link: "https://test-amazon-nine.vercel.app/",
  },
 {
    id: 12,
    titleKey: "project12_title",
    descriptionKey: "project12_description",
    image: "/project/work-test-task.jpg",
    dev: [
      "/svg-icons/reactts.svg",
      "/svg-icons/js.svg",
      "/svg-icons/vitejs.svg",
      "/svg-icons/tailwindcss.svg",
      "/svg-icons/light-redux.svg",
      "/svg-icons/api.svg",

    ],
    link: "https://test-task-2022.vercel.app/",
  },
 {
    id: 13,
    titleKey: "project13_title",
    descriptionKey: "project13_description",
    image: "/project/portfolio-novik.jpg",
    dev: [
      "/svg-icons/html-5.svg",
      "/svg-icons/css3.svg",
    ],
    link: "https://alexprokopev.github.io/portfolio-novik/",
  },
  {
    id: 14,
    titleKey: "project14_title",
    descriptionKey: "project14_description",
    image: "/project/template_shops.jpg",
    dev: [
      "/svg-icons/next-dot.svg",
      "/svg-icons/tailwindcss.svg",
      "/svg-icons/js.svg",
      "/svg-icons/typescript.svg",
      "/svg-icons/development.svg",
      

    ],
    link: "https://tamplate-shop-app-visits.vercel.app/",
  },
  {
    id: 2,
    titleKey: "project2_title",
    descriptionKey: "project2_description",
    image: "/project/cinema.jpg",
    dev: [
      "/svg-icons/reactts.svg",
      "/svg-icons/css3.svg",
      "/svg-icons/js.svg",
      "/svg-icons/api.svg",
    ],
    link: "https://alexprokopev.github.io/goit-react-hw-05-movies/",
  },
  {
    id: 3,
    titleKey: "project3_title",
    descriptionKey: "project3_description",
    image: "/project/landing.jpg",
    dev: ["/svg-icons/js.svg", "/svg-icons/html-5.svg", "/svg-icons/css3.svg"],
    link: "https://konstruct-red.vercel.app/",
  },
  {
    id: 4,
    titleKey: "project4_title",
    descriptionKey: "project4_description",
    image: "/project/mint-switch.jpg",
    dev: [
      "/svg-icons/reactts.svg",
      "/svg-icons/material-ui.svg",
      "/svg-icons/css3.svg",
      "/svg-icons/light-redux.svg",
    ],
    link: "https://mint-switch.vercel.app/",
  },
  {
    id: 5,
    titleKey: "project5_title",
    descriptionKey: "project5_description",
    image: "/project/parser.png",
    dev: [
      "/svg-icons/telegram.svg",
      "/svg-icons/node.svg",
      "/svg-icons/api.svg",
    ],
    link: "https://github.com/AlexProkopev/parserTg",
  },
  {
    id: 6,
    titleKey: "project6_title",
    descriptionKey: "project6_description",
    image: "/project/pet-proj.jpg",
    dev: [
      "/svg-icons/reactts.svg",
      "/svg-icons/material-ui.svg",
      "/svg-icons/css3.svg",
      "/svg-icons/light-redux.svg",
    ],
    link: "https://alexprokopev.github.io/goit-react-hw-08-phonebook",
  },
  {
    id: 7,
    titleKey: "project7_title",
    descriptionKey: "project7_description",
    image: "/project/simply-chokolate.jpg",
    dev: ["/svg-icons/html-5.svg", "/svg-icons/css3.svg", "/svg-icons/js.svg"],
    link: "https://r3enox.github.io/Simply-Chocolate/",
  },
  {
    id: 8,
    titleKey: "project8_title",
    descriptionKey: "project8_description",
    image: "/project/drinkify.jpg",
    dev: [
      "/svg-icons/reactts.svg",
      "/svg-icons/css3.svg",
      "/svg-icons/light-redux.svg",
      "/svg-icons/node.svg",
    ],
    link: "https://soroked.github.io/project-of-futureJS-seniors/",
  },
];